CREATE TABLE users(
  id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  uuid UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  name VARCHAR(100) NOT NULL UNIQUE,
  first_name VARCHAR(255) NOT NULL,
  last_name VARCHAR(255) NOT NULL
)
